### ISSUE TITLE
Incorrect category selection with <THAT> tag

### ISSUE THREAD

**Issue by LorenzCK** [Program-O/Program-O#129]
It appears that Program-O picks the wrong category when a `<THAT>` tag is used for a pattern without a "fallback" category (that is, a category matching the same pattern, but without the `<THAT>`).
Perhaps this is intended, but according to the [Pandorabots documentation](http://docs.pandorabots.com/aiml/that/) and the [official pattern matching specification](http://www.alicebot.org/TR/2005/WD-aiml/#section-pattern-expression-matching-behavior) this seems to be wrong.

### Example

Using a bot with a simple AIML dictionary with only _one_ category:

```xml
<?xml version="1.0"?>
<aiml>
    <category>
        <pattern>HELLO</pattern>
        <that>PREVIOUS RESPONSE</that>
        <template>Wrong answer!</template>
    </category>
</aiml>
```

the bot selects the (only) category even if there is _no_ "that" match. Checking the pattern matching logs, the category is indeed assigned a lower score, but since there is no "fallback" category, it is picked nonetheless.

Adding a category matching the same pattern but _without_ the THAT condition, such as:

```xml
<category>
    <pattern>HELLO</pattern>
    <template>Previous response</template>
</category>
```

gives the correct behavior.

This issue might perhaps be tied to #110.

**Comment by Dave-Morton** [comment]
Hi, @LorenzCK ! Long time no see. :)

If you don't mind, can you provide a sample conversation where you experience this problem? It would help with understanding the problem. If there is only *one* category in the database, and it happens to match the pattern (even if the bot's last response doesn't match the `<that>` tag in that category), it's STILL selecting that category? Is this what's happening? If so, then that's a bit of a problem, but it's not tied to [issue #110](https://github.com/Program-O/Program-O/issues/110).

**Comment by Dave-Morton** [comment]
Ok, I played with this a little, and noticed that the behavior described above was, indeed, happening. Further investigating revealed that there was no provision for situations where an existing THATPATTERN (in the example above, 'PREVIOUS RESPONSE') didn't match the bot's previous response. I've added in that provision, and corrected an incidental bug that allowed empty response arrays to be passed from the scoring function to the selection function. Now, in addition to the scoring behavior being corrected, one of several "blank response" issues has also been fixed. Now I just have to figure out which one... :-\

**Comment by LorenzCK** [comment]
Hi @Dave-Morton ! I'm back pestering you. :)

The issue is kind of an edge case: a category with THAT is usually never used without a matching category lacking the THAT pattern. Thanks for the super quick fix, I'll give it a try on Monday!

**Comment by Dave-Morton** [comment]
Please let me know how you get on with it. :)

**Comment by LorenzCK** [comment]
I've been testing the fix a bit and it appears to work perfectly. :+1:  Thanks!

**Comment by Dave-Morton** [comment]
Glad to hear it. I'll be working with Liz soon (probably over the weekend if she has time) to see about merging the DEV branch into MASTER, so that this issue and a couple of others are addressed in that branch. Please let us know if you have any other problems, and thanks for using Program O. :D

**Comment by Program-O** [comment]
merged with live and pushed a new release 💃 
many thanks to you both

**Comment by thomasnewman1980** [comment]
Hi!
First, sorry for my english, that is not my native language.
I think this issuse is still exist.
Current Local Version: 2.6.10
This is my aiml code:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<aiml version="1.0">
<category>
  <pattern>ANSWER PLEASE</pattern>
    <template>Red or Blue</template>
</category>
<category>
  <pattern>RED</pattern>
    <that>RED OR BLUE</that>
      <template>You choose red.</template>
</category>
<category>
  <pattern>BLUE</pattern>
    <that>RED OR BLUE</that>
      <template>You choose blue</template>
</category>
</aiml>
```
My first question is "red"

> Seeker: red
> Bot: You choose red.

After that:

> Seeker: blue
> Bot: You choose blue

There are no previous message like "RED OR BLUE". As you can see, the ```<that>``` tag doesn't work, or... what is wrong? 

Thanks for the answer!

Best,
Thomas
