### ISSUE TITLE
URL for API?

### ISSUE THREAD

**Issue by BLCKPSTV** [Program-O/Program-O#265]
I managed to install the PHP/SQL example (I'm from a non coding background!) 
But when I go to the test bot I get in the lower left corner this 'ERROR'

```
To get your very own chatbot, visit program-o.com! The URL for the API is currently set as:
http://dewildequinten.be/Program-O-master/chatbot/conversation_start.php.
Please make sure that you edit this file to change the value of the variable $url in this file to reflect the correct URL address of your chatbot, and to remove this message.
```
When I click the link I get a Json file saying this. 
```
{
"convo_id": "9qjgph24gvd3km3oogu1vc2275",
"usersay": "hello",
"botsay": "No AIML category found. This is a Default Response."
}
```
I've added two AIML category via upload. 1 from the link of pre made files and one made by myself. (edited a consisting one.) So they are in place. 

But I still get the test Default Response answer..? 

I'm not very sure what to do next and the installation steps don't really specify this further.

**Comment by Dave-Morton** [comment]
For some reason, your upload of the 2 AIML files didn't take. I was able to access the chatbot by navigating to http://dewildequinten.be/Program-O-master but I get the same default response. Further, I was able to access the debug file for the most recent volley with the chatbot and it verified that no AIML categories were found (you can access the same log file by going to http://dewildequinten.be/Program-O-master/chatbot/debug and logging in, then picking Dave.txt from the selecebox).

__NOTE:__ If what I just told you gives you concern, don't worry. I don't have access to your login credentials. I just know where the debug files are, and know how to access them (and ONLY them).

Anyway, I suggest logging into the admin page (http://dewildequinten.be/Program-O-master/admin) and clicking on Search/Edit AIML or Download AIML. Either of those will work to see what's currently in the database. Please let me know what you find.

**Comment by BLCKPSTV** [comment]
The Download AIML page gives me ItsRelegion (selfmade file) and the StandardReligion.aiml, the Search/Edit page shows me an indexed view of the StandardReligion.aiml 29 pages long.

**Comment by Dave-Morton** [comment]
that is very odd. At this point, I'd either need to see the AIML files so that I can duplicate your Program O install, or be able to log into your current install's admin page so that I can see exactly what's happening. Either way, this conversation should probably become private until we get this resolved. If you have Skype, you can contact me at GeekCaveCreations, or you can email me at dmorton(at)geekcavecreations(dot)com

**Comment by BLCKPSTV** [comment]
pm you!

**Comment by Dave-Morton** [comment]
Ok, part of the problem lies in the fact that you changed the URL for the UI page. The URL for the chatbot should only be changed if you're using a customized interface script (which you are not), so when you can, you should replace the URL to the chatbot to it's original value (you can leave the message empty, however).

Another issue is that you didn't have a "fallback" AIML category in the database to match when nothing else will. I've taken the liberty of putting one in, and so the chatbot will have a different "default" response than what it did before. You're going to want to alter that new default response (since it mentions me) to something more suitable. you can do this easily. Here are the steps:

1. In the admin page, click "Search/Edit AIML"
2. In the PATTERN search box, type in RANDOM PICKUP LINE
3. Click on the value under the TEMPLATE field for that AIML category (there should only be one category listed)
4. change the response to whatever you like
5. Click on any other area of the page (preferably on a blank area of the page

And that's it. Simple! If you have trouble, or have any other questions please let me know.

**Comment by BLCKPSTV** [comment]
So this is the php end of the jquery/index.php

```
// Experimental code
$base_URL = 'http://' . $_SERVER['HTTP_HOST'];                                   // set domain name for the script
$this_path = str_replace(DIRECTORY_SEPARATOR, '/', realpath(dirname(__FILE__)));  // The current location of this file, normalized to use forward slashes
$this_path = str_replace($_SERVER['DOCUMENT_ROOT'], $base_URL, $this_path);       // transform it from a file path to a URL
$url = str_replace('gui/jquery', 'chatbot/conversation_start.php', $this_path);   // and set it to the correct script location
/*
  Example URL's for use with the chatbot API
  $url = 'http://api.program-o.com/v2.3.1/chatbot/';
  $url = 'http://localhost/Program-O/Program-O/chatbot/conversation_start.php';
  $url = 'chat.php';
*/
$url = 'http://api.program-o.com/v2.3.1/chatbot/';

#$display = "The URL for the API is currently set as:<br />\n$url.<br />\n";
#$display .= 'Test this to make sure it is correct by <a href="' . $url . '?say=hello">clicking here</a>. Then remove this message from gui/jquery/index.php' . PHP_EOL;
#$display .= 'And don\'t forget to upload your AIML files in the admin area otherwise you will not get a response!' . PHP_EOL;
#$display = '';
```
Is this the correct layout i.e. did I uncomment (#) the correct lines of code? 

I've already changed the RANDOM PICKUP LINE.

**Comment by BLCKPSTV** [comment]
changed it to this: 

```
// Experimental code
$base_URL = 'http://' . $_SERVER['HTTP_HOST'];                                   // set domain name for the script
$this_path = str_replace(DIRECTORY_SEPARATOR, '/', realpath(dirname(__FILE__)));  // The current location of this file, normalized to use forward slashes
$this_path = str_replace($_SERVER['DOCUMENT_ROOT'], $base_URL, $this_path);       // transform it from a file path to a URL
$url = str_replace('gui/jquery', 'chatbot/conversation_start.php', $this_path);   // and set it to the correct script location
/*
  Example URL's for use with the chatbot API
  $url = 'http://api.program-o.com/v2.3.1/chatbot/';
  $url = 'http://localhost/Program-O/Program-O/chatbot/conversation_start.php';
  $url = 'chat.php';
  $url = 'http://localhost/Program-O/Program-O/chatbot/conversation_start.php';
$url = 'http://api.program-o.com/v2.3.1/chatbot/';
*/


#$display = "The URL for the API is currently set as:<br />\n$url.<br />\n";
#$display .= 'Test this to make sure it is correct by <a href="' . $url . '?say=hello">clicking here</a>. Then remove this message from gui/jquery/index.php' . PHP_EOL;
#$display .= 'And don\'t forget to upload your AIML files in the admin area otherwise you will not get a response!' . PHP_EOL;
#$display = '';

```

Now it started to work on hello, but then after few other questions I got this error below.
Something went wrong! Error = SyntaxError: Unexpected end of JSON input. Can you me If this means my list of usable answers is depleted? 

Also testing my bot via the list item talk to 'name of bot' gives me a blank page with a 404 ERROR

The requested URL /Program-O-master/gui/jquery/bot_id=1 was not found on this server.

`Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.`

**Comment by Dave-Morton** [comment]
>The requested URL /Program-O-master/gui/jquery/bot_id=1 was not found on this server.

>Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

There should be a question mark between that last forward slash (/) and bot_id, so it should look like this:

`/Program-O-master/gui/jquery/?bot_id=1`

That's a bug in the admin script. I'll work that out for the next bug fix release.

**Comment by patrickschur** [comment]
@Dave-Morton The bug is already fixed in the dev branch.

**Comment by BLCKPSTV** [comment]
Do I need to do something to get this working? I still get the 404 error...?
http://dewildequinten.be/Program-O-master/gui/jquery/bot_id=1

**Comment by BLCKPSTV** [comment]
Or better in which file and which line do I have to change this?

**Comment by Dave-Morton** [comment]
The problem there is in index.php in the root directory. There is a bug that is causing this. In the text editor of your choice, open index.php and look for the following line:

`$qs = '';`
and change it to this:

`$qs = '?';`

that will fix the issue. This bug has been fixed in the `DEV` branch, but hasn't made it into `MASTER` yet. I just don't see reinstalling Program O for something as minor as that. I'll be merging the two branches in the next few days, as soon as I make sure that no other bugs will be introduced by doing so. :)

**Comment by Program-O** [comment]
closed as fixed with no response for over 30 days
