### ISSUE TITLE
get set variables not working

### ISSUE THREAD

**Issue by nbl7** [Program-O/Program-O#436]
Hi there,

I've been trying to install Program-o with different sets of AIML files, but every time it seems the program doesn't save variables by using the tag `<set>`

Here an example. I've uploaded only this AIML file:

```
<category>
  <pattern>_MY NAME IS *</pattern>
  <template>
    Ok. I will remind that.
    <think><set name="username"><star/></set></think>
  </template>
</category>
<category>
  <pattern>_SAY MY NAME</pattern>
  <template><get name="username"/>!</template>
</category>
```

And this is the result:
```
User: my name is Mike
Bot: Ok. I will remind that.
User: say my name
Bot: Seeker !
```

Do you have any idea why?

Thank you
Best
A.

**Comment by patrickschur** [comment]
You have an underscore in your pattern which means one or more words. Remove the underscore or use `<star index="2"/>` to get the name in the first pattern. I would also suggest you to put a whitespace between the underscore and the word (if the underscore is necessary).

Best regards
Patrick

**Comment by nbl7** [comment]
That was really helpful.
Thank you very much @patrickschur.

**Comment by nbl7** [comment]
Hi there,
I am actually still having problems with `get` and `set` tags.

It seems the program doesn't save any variables. Here is the code:

```
<category><pattern>CALL ME *</pattern>
<template>
  <think><set name="personality">average</set></think>
  <random>
  <li>Hey</li>
  <li>Hi,</li>
  <li>Hi there</li>
  <li>What's up,</li>
  <li>How are you,</li>
  </random> <set name="user_name"><star/></set>.
</template>
</category>

<category><pattern>MY NAME</pattern>
<template>
<condition name="user_name">  
  <li value="*">You said your name is <get name="user_name"/>?</li>  
  <li>I don't know.  What is your name?</li></condition>
</template>
</category>
```

But when I ask my name it always return `i don't know. What is your name?`

This is just a example, but it never save any variable with the `set` tag.

Where can I find the code that save the variables? Where are they saved? In the session or in the database?

Thank you
nbl7

**Comment by patrickschur** [comment]
I guess you are using the master branch of Program-O? There is a bug in the master branch which can't handle condition tags right. I suggest you to use the dev branch of Program-O. I've already fixed the issue in the dev branch.

> Where can I find the code that save the variables?

You can find the code in the file `chatbot/core/aiml/parse_aiml_as_xml.php` at line 555 (dev branch).

>  Where are they saved? In the session or in the database?

The variables are saved in your database and the table is called `client_properties`.

Regards
Patrick

**Comment by nbl7** [comment]
Thanks for the answer @patrickschur.

I switch to the `dev` branch but unfortunately it is still not working.
I am debugging and this is what I discover.

I've uploaded only this file:
```
<?xml version="1.0" encoding="UTF-8"?>
<aiml version="1.0">
<category><pattern>MY NAME</pattern>
	<template>
		You said your name is <get name="name"/>?
	</template>
</category>
<category>
	<pattern>CALL ME *</pattern>
	<template>
		<think><set name="personality">average</set></think>
		<random> 
			<li>Hey</li>
		  <li>Hi,</li>
		</random>
		<set name="name"><star/></set>.
	</template>
</category>
</aiml>

```

So, when I write `call me MYNAME` it does save in the DB two records:
` name: name, value: MYNAME `
` name: ip_address, value: MYIPADDRESS `  

The problem is that when I call `my name` it also save other two records:
` name: name, value: Seeker `
` name: ip_address, value: MYIPADDRESS `  

So that is probably why it is not working.
When I call a `get` it sets a new value with the undefined name.

I wanted to try with a new variable called `nname`. And it does save it. But when I call the `get name="nname"` a new record is added to the DB:
` name: name, value: Seeker `

And the result on the answer is still `undefined`

Any ideas?

Thank you
nbl7

**Comment by patrickschur** [comment]
I see the problem... but it should work if you rename the variable name to `new_name`. Can you test the following code (again)? Because I tested this and it worked for me.

```xml
<category><pattern>MY NAME</pattern>
	<template>
		You said your name is <get name="new_name"/>?
	</template>
</category>
<category>
	<pattern>CALL ME *</pattern>
	<template>
		<think><set name="personality">average</set></think>
		<random> 
			<li>Hey</li>
		  <li>Hi,</li>
		</random>
		<set name="new_name"><star/></set>.
	</template>
</category>
```

Example conversation:
```txt
Seeker: Call me Patrick.
Bot: Hey Patrick.
Seeker: My name?
Bot: You said your name is Patrick?
```

Until I fixed the issue (if you can call it an issue) don't use `name` or `ip` as variable names.

If renaming the variable doesn't work can you send us the content of your log file? You can find the log file `error.log` in the `logs` folder.

**Comment by nbl7** [comment]
Ok, now it seems to work but only in the `page=demochat`

I think I understand what is the problem.
The `convo_id` change every time a make an Ajax call or I call directly the URL 
`/chatbot/conversation_start.php?say=hello`

It shouldn't, right?

p.s. There was no `error.log` in the `logs` folder

Thank you!
nbl7

**Comment by nbl7** [comment]
Ok, yes. Now that I am passing a `convo_id` it's working.

Sorry but I didn't read anywhere that you should pass the `session_id`

Thanks a lot for the support.

**Comment by patrickschur** [comment]
@nbl7 Knowing you're using an Ajax call makes it easier for me to help you. :) You just have to send the `convo_id` back. Otherwise you get always a new `convo_id`.

If there is no `error.log` this is a good sign.
